apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: summarize-app-client
          image: myregistry.com/summarize-app-client:latest
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-url
                  key: url
      imagePullSecrets:
        - name: regcred
